name: build-images

on:
  push:

jobs:
  build-images:
    name: build-images
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    uses: ./.github/workflows/_build-image.yml
    with:
      arch: ${{ matrix.arch }}
      image-tag: ci-${{ github.sha }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
